name: Generate Pacman Graph

on:
  schedule:
    # Har raat 12 baje run hoga
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate-Pacman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: k-phy/pacman-contribution-graph@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: Bhavesh1116
          build_dir: dist

      - name: Push Image to Output Branch
        uses: crazy-max/gh-action-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
